# Generated by Django 5.1.2 on 2025-01-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tm_main',
            name='legislation_description_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tm_main',
            name='marktype_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
