# Generated by Django 5.1.2 on 2025-03-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademarks', '0003_tm_main_mark_significant_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tm_footnote',
            name='footnote_change_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tm_footnote',
            name='footnote_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
