# Generated by Django 5.1.1 on 2025-07-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMain',
            fields=[
                ('application_number', models.TextField(primary_key=True, serialize=False)),
                ('extension_number', models.TextField()),
                ('design_status', models.TextField()),
                ('filing_date', models.DateField()),
            ],
            options={
                'verbose_name': 'ID – application main',
                'db_table': '"id_csv_2024_03_07"."application_main"',
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
