# Generated by Django 5.1.1 on 2025-07-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial_designs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationClassification',
            fields=[
                ('application_number', models.TextField(primary_key=True, serialize=False)),
                ('extension_number', models.TextField()),
                ('classification_kind_code', models.TextField()),
                ('classification_kind', models.TextField()),
                ('classification_number', models.TextField()),
                ('classification_primary', models.TextField()),
                ('classification_sub', models.TextField()),
                ('classification_sub_sub', models.TextField()),
                ('product_description', models.TextField()),
            ],
            options={
                'verbose_name': 'ID – application classification',
                'db_table': '"id_csv_2024_03_07"."application_classification"',
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ApplicationCorrection',
            fields=[
                ('application_number', models.TextField(primary_key=True, serialize=False)),
                ('extension_number', models.TextField()),
                ('publication_identifier', models.TextField()),
                ('publication_section', models.TextField()),
                ('correction_date', models.DateField()),
            ],
            options={
                'verbose_name': 'ID – application correction',
                'db_table': '"id_csv_2024_03_07"."application_correction"',
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ApplicationDescription',
            fields=[
                ('application_number', models.TextField(primary_key=True, serialize=False)),
                ('extension_number', models.TextField()),
                ('design_description_text_sequence_number', models.IntegerField()),
                ('design_description_language_code', models.TextField()),
                ('design_description', models.TextField()),
            ],
            options={
                'verbose_name': 'ID – application description',
                'db_table': '"id_csv_2024_03_07"."application_description"',
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ApplicationDescriptionTxtFormat',
            fields=[
                ('application_number', models.TextField(primary_key=True, serialize=False)),
                ('extension_number', models.TextField()),
                ('design_description_language_code', models.TextField()),
                ('design_description', models.TextField()),
            ],
            options={
                'verbose_name': 'ID – application description TXT-format',
                'db_table': '"id_csv_2024_03_07"."application_description_txt_format"',
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ApplicationImage',
            fields=[
                ('application_number', models.TextField(primary_key=True, serialize=False)),
                ('extension_number', models.TextField()),
                ('filename', models.TextField()),
                ('colour', models.TextField()),
                ('colour_type', models.TextField()),
                ('image_kind', models.TextField()),
                ('image_kind_code', models.TextField()),
            ],
            options={
                'verbose_name': 'ID – application image',
                'db_table': '"id_csv_2024_03_07"."application_image"',
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ApplicationInterestedParty',
            fields=[
                ('application_number', models.TextField(primary_key=True, serialize=False)),
                ('extension_number', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('organization_name', models.TextField()),
                ('role', models.TextField()),
                ('role_code', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('country_code', models.TextField()),
                ('postal_code', models.TextField()),
                ('province_state', models.TextField()),
            ],
            options={
                'verbose_name': 'ID – application interested party',
                'db_table': '"id_csv_2024_03_07"."application_interested_party"',
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AssignmentCorrection',
            fields=[
                ('assignment_number', models.TextField(primary_key=True, serialize=False)),
                ('publication_identifier', models.TextField()),
                ('publication_section', models.TextField()),
                ('correction_date', models.DateField()),
            ],
            options={
                'verbose_name': 'ID – assignment correction',
                'db_table': '"id_csv_2024_03_07"."assignment_correction"',
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AssignmentInterestedParty',
            fields=[
                ('assignment_number', models.TextField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('organization_name', models.TextField()),
                ('role', models.TextField()),
                ('role_code', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('country_code', models.TextField()),
                ('postal_code', models.TextField()),
                ('province_state', models.TextField()),
            ],
            options={
                'verbose_name': 'ID – assignment interested party',
                'db_table': '"id_csv_2024_03_07"."assignment_interested_party"',
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AssignmentMain',
            fields=[
                ('assignment_number', models.TextField(primary_key=True, serialize=False)),
                ('application_number', models.TextField()),
                ('extension_number', models.TextField()),
                ('assignment_registration_date', models.DateField()),
                ('assignment_status_type', models.TextField()),
                ('assignment_status', models.TextField()),
                ('assignment_type_code', models.TextField()),
                ('assignment_type', models.TextField()),
                ('legal_disclaimer', models.TextField()),
                ('ownership_change_prior_to_filing', models.TextField()),
            ],
            options={
                'verbose_name': 'ID – assignment main',
                'db_table': '"id_csv_2024_03_07"."assignment_main"',
                'abstract': False,
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
