# Generated by Django 5.1.2 on 2025-01-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademarks', '0002_tm_main_legislation_description_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tm_main',
            name='mark_significant_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tm_main',
            name='evidence_of_use_indicator',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tm_main',
            name='trademark_class_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
