# Generated by Django 5.0.6 on 2024-06-11 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PT_Main',
            fields=[
                ('patent_number', models.IntegerField(primary_key=True, serialize=False)),
                ('filing_date', models.DateField()),
                ('grant_date', models.DateField()),
                ('application_status_code', models.CharField(max_length=2)),
                ('application_type_code', models.CharField(max_length=10)),
                ('application_patent_title_french', models.CharField(max_length=255)),
                ('application_patent_title_english', models.CharField(max_length=255)),
                ('bibliographic_file_extract_date', models.DateField()),
                ('country_of_publication_code', models.CharField(max_length=2)),
                ('document_kind_type', models.CharField(max_length=5)),
                ('examination_request_date', models.DateField()),
                ('filing_country_code', models.CharField(max_length=2)),
                ('language_of_filing_code', models.CharField(max_length=2)),
                ('license_for_sale_indicator', models.BooleanField()),
                ('pct_application_number', models.CharField(max_length=50)),
                ('pct_publication_number', models.CharField(max_length=50)),
                ('pct_publication_date', models.DateField()),
                ('parent_application_number', models.IntegerField()),
                ('pct_article_22_39_fulfilled_date', models.DateField()),
                ('pct_section_371_date', models.DateField()),
                ('pct_publication_country_code', models.CharField(max_length=2)),
                ('publication_kind_type', models.CharField(max_length=5)),
                ('printed_as_amended_country_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PT_Priority_Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_application_patent_number', models.CharField(max_length=50)),
                ('priority_claim_kind_code', models.CharField(max_length=15)),
                ('priority_claim_country_code', models.CharField(max_length=2)),
                ('priority_claim_country', models.CharField(max_length=100)),
                ('priority_claim_calendar_dt', models.DateField()),
                ('patent_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patents.pt_main')),
            ],
        ),
        migrations.CreateModel(
            name='PT_IPC_Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipc_classification_sequence_number', models.IntegerField()),
                ('ipc_version_date', models.DateField()),
                ('classification_level', models.CharField(max_length=1)),
                ('classification_status_code', models.CharField(max_length=1)),
                ('classification_status', models.CharField(max_length=1)),
                ('ipc_section_code', models.CharField(max_length=1)),
                ('ipc_section', models.CharField(max_length=50)),
                ('ipc_class_code', models.CharField(max_length=10)),
                ('ipc_class', models.CharField(max_length=100)),
                ('ipc_subclass_code', models.CharField(max_length=10)),
                ('ipc_subclass', models.CharField(max_length=100)),
                ('ipc_main_group_code', models.CharField(max_length=10)),
                ('ipc_group', models.IntegerField()),
                ('ipc_subgroup_code', models.CharField(max_length=10)),
                ('ipc_subgroup', models.CharField(max_length=100)),
                ('patent_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patents.pt_main')),
            ],
            options={
                'db_table': 'pt_ipc_classification',
                'unique_together': {('patent_number', 'ipc_classification_sequence_number')},
            },
        ),
        migrations.CreateModel(
            name='PT_Interested_Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type_code', models.CharField(max_length=50)),
                ('applicant_type_code', models.CharField(max_length=50)),
                ('interested_party_type_code', models.CharField(max_length=10)),
                ('interested_party_type', models.CharField(max_length=50)),
                ('owner_enable_date', models.DateField()),
                ('ownership_end_date', models.DateField(blank=True, null=True)),
                ('party_name', models.CharField(max_length=255)),
                ('party_address_line_1', models.CharField(max_length=255)),
                ('party_address_line_2', models.CharField(blank=True, max_length=255)),
                ('party_address_line_3', models.CharField(blank=True, max_length=255)),
                ('party_address_line_4', models.CharField(blank=True, max_length=255)),
                ('party_address_line_5', models.CharField(blank=True, max_length=255)),
                ('party_city', models.CharField(max_length=100)),
                ('party_province_code', models.CharField(blank=True, max_length=10)),
                ('party_province', models.CharField(blank=True, max_length=100)),
                ('party_postal_code', models.CharField(blank=True, max_length=20)),
                ('party_country_code', models.CharField(max_length=2)),
                ('party_country', models.CharField(max_length=100)),
                ('patent_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patents.pt_main')),
            ],
            options={
                'unique_together': {('patent_number', 'party_name')},
            },
        ),
        migrations.CreateModel(
            name='PT_Disclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_of_filing_code', models.CharField(max_length=2)),
                ('disclosure_text', models.TextField()),
                ('disclosure_text_sequence_number', models.IntegerField()),
                ('patent_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patents.pt_main')),
            ],
            options={
                'unique_together': {('patent_number', 'disclosure_text_sequence_number')},
            },
        ),
        migrations.CreateModel(
            name='PT_Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_of_filing_code', models.CharField(max_length=2)),
                ('claims_text', models.TextField()),
                ('claim_text_sequence_number', models.IntegerField()),
                ('patent_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patents.pt_main')),
            ],
            options={
                'unique_together': {('patent_number', 'claim_text_sequence_number')},
            },
        ),
        migrations.CreateModel(
            name='PT_Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_of_filing_code', models.CharField(max_length=2)),
                ('abstract_language_code', models.CharField(max_length=2)),
                ('abstract_text', models.TextField()),
                ('abstract_text_sequence_number', models.IntegerField()),
                ('patent_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patents.pt_main')),
            ],
            options={
                'unique_together': {('patent_number', 'abstract_text_sequence_number')},
            },
        ),
    ]
