# Generated by Django 5.0.6 on 2024-07-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_main',
            name='examination_request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='filing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='grant_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='parent_application_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='pct_article_22_39_fulfilled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='pct_publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='pct_section_371_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
