# Generated by Django 5.0.6 on 2024-07-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0002_alter_pt_main_examination_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_main',
            name='application_patent_title_french',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
