# Generated by Django 5.0.6 on 2024-07-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0003_alter_pt_main_application_patent_title_french'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_main',
            name='application_patent_title_english',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
