# Generated by Django 5.0.6 on 2024-07-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0004_alter_pt_main_application_patent_title_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_main',
            name='application_patent_title_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='application_status_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='application_type_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='bibliographic_file_extract_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='country_of_publication_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='document_kind_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='filing_country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='language_of_filing_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='license_for_sale_indicator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='pct_application_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='pct_publication_country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='pct_publication_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='printed_as_amended_country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='publication_kind_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
