# Generated by Django 5.0.6 on 2024-07-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0005_alter_pt_main_application_patent_title_english_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_main',
            name='application_patent_title_english',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='application_patent_title_french',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='application_status_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='application_type_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='country_of_publication_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='document_kind_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='filing_country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='language_of_filing_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='license_for_sale_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='parent_application_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='patent_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='pct_publication_country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='printed_as_amended_country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pt_main',
            name='publication_kind_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
