# Generated by Django 5.0.6 on 2024-07-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0006_alter_pt_main_application_patent_title_english_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pt_priority_claim',
            unique_together={('patent_number', 'foreign_application_patent_number')},
        ),
    ]
