# Generated by Django 5.0.6 on 2024-07-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0007_alter_pt_priority_claim_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_ipc_classification',
            name='ipc_group',
            field=models.CharField(max_length=10),
        ),
    ]
