# Generated by Django 5.0.6 on 2024-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0008_alter_pt_ipc_classification_ipc_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_ipc_classification',
            name='ipc_class',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pt_ipc_classification',
            name='ipc_group',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pt_ipc_classification',
            name='ipc_section',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pt_ipc_classification',
            name='ipc_subclass',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pt_ipc_classification',
            name='ipc_subgroup',
            field=models.CharField(max_length=250),
        ),
    ]
