# Generated by Django 5.0.6 on 2024-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0010_alter_pt_ipc_classification_ipc_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_ipc_classification',
            name='ipc_group',
            field=models.CharField(max_length=500),
        ),
    ]
