# Generated by Django 5.0.6 on 2024-07-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0011_alter_pt_ipc_classification_ipc_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pt_interested_party',
            unique_together={('patent_number', 'party_name', 'owner_enable_date')},
        ),
        migrations.AlterModelTable(
            name='pt_interested_party',
            table='pt_interested_party',
        ),
    ]
