# Generated by Django 5.0.6 on 2024-07-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0012_alter_pt_interested_party_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_interested_party',
            name='owner_enable_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
