# Generated by Django 5.1.1 on 2024-10-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0013_alter_pt_interested_party_owner_enable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_abstract',
            name='patent_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstracts', to='patents.pt_main'),
        ),
        migrations.AlterField(
            model_name='pt_claim',
            name='patent_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='patents.pt_main'),
        ),
        migrations.AlterField(
            model_name='pt_disclosure',
            name='patent_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='patents.pt_main'),
        ),
    ]
