# Generated by Django 5.1.1 on 2024-10-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0014_alter_pt_abstract_patent_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_main',
            name='patent_number',
            field=models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
