# Generated by Django 5.1.1 on 2024-10-16 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0015_alter_pt_main_patent_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_interested_party',
            name='patent_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_parties', to='patents.pt_main'),
        ),
    ]
