# Generated by Django 5.1.1 on 2024-10-16 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0016_alter_pt_interested_party_patent_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_ipc_classification',
            name='patent_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipc_classifications', to='patents.pt_main'),
        ),
        migrations.AlterField(
            model_name='pt_priority_claim',
            name='patent_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_claims', to='patents.pt_main'),
        ),
    ]
